import React, { useState, useEffect, useRef } from 'react';
import { Sparkles, Map, MapPin, Calendar, Loader2, Key, ChevronRight, Plane, Coffee, Camera, Footprints, Moon, Heart, Clock, Printer, History, Share2, Check } from 'lucide-react';
import { useItineraryGenerator } from './useItineraryGenerator';
import { useWeather } from './useWeather';
import { useTripHistory } from './useTripHistory';
import StopModal from './StopModal';
import DailyMapModal from './DailyMapModal';

export default function App() {
  const [userInput, setUserInput] = useState('');
  const [selectedStop, setSelectedStop] = useState(null);
  const [selectedDayForMap, setSelectedDayForMap] = useState(null);
  const [showHistory, setShowHistory] = useState(false);
  const [copied, setCopied] = useState(false);
  const historyMenuRef = useRef(null);

  const { status, itinerary, errorMsg, generate, setItinerary, setStatus } = useItineraryGenerator();
  const { weather, loading: weatherLoading } = useWeather(itinerary?.destination);
  const { history, saveToHistory } = useTripHistory();

  // Save successful itinerary to history
  useEffect(() => {
    if (status === 'success' && itinerary) {
      saveToHistory(itinerary);
    }
  }, [status, itinerary, saveToHistory]);

  // Click outside to close history menu
  useEffect(() => {
    function handleClickOutside(event) {
      if (historyMenuRef.current && !historyMenuRef.current.contains(event.target)) {
        setShowHistory(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const handleSuggestionClick = (suggestion) => {
    setUserInput(suggestion);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (userInput.trim()) {
      generate(userInput, ''); // Removed apiKey since we removed the setup panel
    }
  };

  const loadPastTrip = (pastTrip) => {
    setItinerary(pastTrip);
    setStatus('success');
    setShowHistory(false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handlePrint = () => {
    window.print();
  };

  const handleShare = async () => {
    if (!itinerary) return;

    let text = `✈️ WanderAI Itinerary: ${itinerary.trip_title}\n📍 Destination: ${itinerary.destination}\n📅 Duration: ${itinerary.duration_days} Days\n\n`;

    itinerary.days.forEach(day => {
      text += `\n--- Day ${day.day}: ${day.title} ---\n`;
      day.stops.forEach(stop => {
        text += `• ${stop.time} - ${stop.name} (${stop.cost_estimate || 'Varies'})\n  ${stop.notes}\n`;
      });
    });

    text += `\n✨ Generated by WanderAI`;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy!', err);
    }
  };

  const getCategoryTheme = (category) => {
    const cat = category?.toLowerCase() || '';
    if (cat.includes('food') || cat.includes('restaurant') || cat.includes('dining')) return { class: 'cat-food', icon: <Coffee size={20} /> };
    if (cat.includes('sightseeing') || cat.includes('attraction') || cat.includes('landmark')) return { class: 'cat-attraction', icon: <Camera size={20} /> };
    if (cat.includes('park') || cat.includes('nature')) return { class: 'cat-nature', icon: <Map size={20} /> };
    if (cat.includes('transport') || cat.includes('flight') || cat.includes('train')) return { class: 'cat-transport', icon: <Plane size={20} /> };
    if (cat.includes('activity') || cat.includes('culture') || cat.includes('museum')) return { class: 'cat-culture', icon: <Footprints size={20} /> };
    if (cat.includes('rest') || cat.includes('hotel')) return { class: 'cat-rest', icon: <Moon size={20} /> };
    return { class: 'cat-default', icon: <MapPin size={20} /> };
  };

  return (
    <div className="app-container">
      
      {/* Header */}
      <header className="app-header">
        <div className="logo-container">
          <div className="logo-icon">
            <Plane size={24} color="white" />
          </div>
          <div className="logo-text">
            <h1 className="title-font">Wander<span>AI</span></h1>
            <p>Smart Itinerary Generator</p>
          </div>
        </div>
        
        {/* History Dropdown */}
        <div className="history-dropdown" ref={historyMenuRef}>
          <button 
            className="btn-outline" 
            onClick={() => setShowHistory(!showHistory)}
          >
            <History size={16} />
            My Trips
          </button>
          
          {showHistory && (
            <div className="history-menu animate-fade-in">
              {history.length === 0 ? (
                <div className="no-history">No past trips found.</div>
              ) : (
                history.map((trip) => (
                  <div key={trip.id} className="history-item" onClick={() => loadPastTrip(trip)}>
                    <div className="history-item-title">{trip.trip_title || trip.destination}</div>
                    <div className="history-item-date">
                      {trip.duration_days} days • {new Date(trip.createdAt).toLocaleDateString()}
                    </div>
                  </div>
                ))
              )}
            </div>
          )}
        </div>
      </header>

      {/* Main Form */}
      <form onSubmit={handleSubmit} className="form-card">
        <h2 className="title-font">Where do you want to go?</h2>
        <textarea
          className="main-textarea"
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          placeholder="e.g. 3 days in Paris with a focus on art, history, and gastronomy..."
        />

        <div className="form-actions">
          <div className="preset-container">
            <span className="preset-label">Try a preset</span>
            <button type="button" onClick={() => handleSuggestionClick('3 days in Tokyo with a focus on modern tech and pop culture')} className="preset-btn preset-btn-blue">🗼 Tokyo Neon</button>
            <button type="button" onClick={() => handleSuggestionClick('3 days in Paris with a focus on art, history, and gastronomy')} className="preset-btn preset-btn-red">🥐 Paris Art</button>
            <button type="button" onClick={() => handleSuggestionClick('2 days in Rome')} className="preset-btn preset-btn-yellow">🏛️ Rome Classic</button>
          </div>
          
          <button 
            type="submit" 
            className="btn-primary"
            disabled={status === 'loading'}
          >
            {status === 'loading' ? <Loader2 size={20} className="animate-spin-slow" /> : <Sparkles size={20} />}
            {status === 'loading' ? 'Generating itinerary...' : 'Generate Itinerary'}
          </button>
        </div>
      </form>

      {/* Error States */}
      {status === 'error' && errorMsg && (
        <div className="alert-card animate-fade-in">
          <span className="alert-title">Unable to generate itinerary</span>
          <span className="alert-desc">{errorMsg}</span>
        </div>
      )}

      {status === 'empty' && errorMsg && (
        <div className="alert-card warning animate-fade-in">
          <span className="alert-title">More info needed</span>
          <span className="alert-desc">{errorMsg}</span>
        </div>
      )}

      {/* Itinerary Results */}
      {status === 'success' && itinerary && (
        <div className="animate-fade-in">
          <div className="itinerary-header">
            <h2 className="title-font">{itinerary.trip_title}</h2>
            <div className="itinerary-meta">
              <span><MapPin size={18} /> {itinerary.destination}</span>
              <span><Calendar size={18} /> {itinerary.duration_days} Days</span>
            </div>
          </div>

          {/* New Actions Bar (Weather & Print) */}
          <div className="itinerary-actions animate-slide-up">
            {weatherLoading ? (
              <div className="weather-widget" style={{ margin: 0 }}>
                <Loader2 size={20} className="animate-spin-slow weather-icon" /> Fetching weather...
              </div>
            ) : weather ? (
              <div className="weather-widget" style={{ margin: 0 }}>
                <span style={{ fontSize: '1.2rem' }}>{weather.emoji}</span>
                <span>{weather.temp}°C, {weather.description}</span>
              </div>
            ) : null}

            <button className="btn-outline" onClick={handlePrint}>
              <Printer size={18} /> Print PDF
            </button>
            
            <button className="btn-outline" onClick={handleShare}>
              {copied ? <Check size={18} color="#059669" /> : <Share2 size={18} />}
              {copied ? 'Copied!' : 'Copy to Share'}
            </button>
          </div>

          <div className="days-container">
            {itinerary.days.map((day, dIndex) => (
              <div 
                key={dIndex} 
                className="day-card animate-slide-up"
                style={{ animationDelay: `${dIndex * 0.15}s` }}
              >
                <div className="day-header">
                  <div className="day-header-content">
                    <div>
                      <h3 className="title-font">Day {day.day}</h3>
                      <p>{day.title}</p>
                    </div>
                    <button 
                      className="route-map-btn" 
                      onClick={() => setSelectedDayForMap(day)}
                    >
                      <Map size={16} /> View Route Map
                    </button>
                  </div>
                </div>

                <div className="stops-list">
                  {day.stops.map((stop, sIndex) => {
                    const theme = getCategoryTheme(stop.category);
                    return (
                      <div 
                        key={stop.id || sIndex} 
                        className={`stop-card ${theme.class}`}
                        onClick={() => setSelectedStop(stop)}
                      >
                        <div className="icon-container">
                          {theme.icon}
                        </div>
                        
                        <div className="stop-details">
                          <div className="stop-title-row">
                            <h4>{stop.name}</h4>
                            <span className="stop-time"><Clock size={12} style={{ display: 'inline', verticalAlign: '-1px', marginRight: '2px' }}/> {stop.time}</span>
                            {stop.cost_estimate && (
                              <span className="cost-badge">{stop.cost_estimate}</span>
                            )}
                          </div>
                          <p className="stop-description">
                            {stop.notes}
                          </p>
                        </div>
                        
                        <div className="stop-chevron">
                          <ChevronRight size={20} />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="app-footer">
        <Heart size={16} /> Made with WanderAI — Your smart travel companion.
      </footer>

      {/* Stop Detail Modal (Native Dialog) */}
      <StopModal stop={selectedStop} destination={itinerary?.destination} onClose={() => setSelectedStop(null)} />
      
      {/* Daily Route Map Modal */}
      <DailyMapModal dayData={selectedDayForMap} destination={itinerary?.destination} onClose={() => setSelectedDayForMap(null)} />
    </div>
  );
}
